apiVersion: 1

notifiers:
  - name: Email Alerts
    type: email
    uid: email_alerts
    org_id: 1
    is_default: true
    settings:
      addresses: admin@example.com
    secure_settings: {}

  - name: Slack Alerts
    type: slack
    uid: slack_alerts
    org_id: 1
    is_default: false
    settings:
      url: https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK
      recipient: "#alerts"
      mentionChannel: "here"
    secure_settings: {}

  - name: Webhook Alerts
    type: webhook
    uid: webhook_alerts
    org_id: 1
    is_default: false
    settings:
      url: http://localhost:8000/api/alerts/webhook
      httpMethod: POST
      maxAlerts: 100
    secure_settings: {} 