apiVersion: v1
kind: Namespace
metadata:
  name: calculator-staging
  labels:
    name: calculator-staging
    environment: staging
    team: calculator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-config-staging
  namespace: calculator-staging
data:
  ENVIRONMENT: "staging"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  RATE_LIMIT_PER_MINUTE: "100"
  ENABLE_METRICS: "true"
  ENABLE_ABS_DIFF: "true"
  ENABLE_HISTORY: "true"
  DATABASE_URL: "postgresql+asyncpg://calculator:password@postgres-staging:5432/calculator_staging"
  REDIS_URL: "redis://redis-staging:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: calculator-secrets-staging
  namespace: calculator-staging
type: Opaque
data:
  SECRET_KEY: "c3RhZ2luZy1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u"  # base64 encoded
  DB_PASSWORD: "cGFzc3dvcmQ="  # base64 encoded 