apiVersion: v1
kind: Namespace
metadata:
  name: calculator-prod
  labels:
    name: calculator-prod
    environment: production
    team: calculator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-config-prod
  namespace: calculator-prod
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "WARNING"
  RATE_LIMIT_PER_MINUTE: "60"
  ENABLE_METRICS: "true"
  ENABLE_ABS_DIFF: "true"
  ENABLE_HISTORY: "true"
  DATABASE_URL: "postgresql+asyncpg://calculator:password@postgres-prod:5432/calculator_prod"
  REDIS_URL: "redis://redis-prod:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: calculator-secrets-prod
  namespace: calculator-prod
type: Opaque
data:
  SECRET_KEY: "cHJvZC1zZWNyZXQta2V5LW11c3QtYmUtc2VjdXJlLWFuZC1sb25n"  # base64 encoded
  DB_PASSWORD: "cHJvZC1wYXNzd29yZA=="  # base64 encoded 