apiVersion: v1
kind: Namespace
metadata:
  name: calculator-dev
  labels:
    name: calculator-dev
    environment: development
    team: calculator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-config-dev
  namespace: calculator-dev
data:
  ENVIRONMENT: "development"
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  RATE_LIMIT_PER_MINUTE: "1000"
  ENABLE_METRICS: "true"
  ENABLE_ABS_DIFF: "true"
  ENABLE_HISTORY: "true"
  DATABASE_URL: "postgresql+asyncpg://calculator:password@postgres-dev:5432/calculator_dev"
  REDIS_URL: "redis://redis-dev:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: calculator-secrets-dev
  namespace: calculator-dev
type: Opaque
data:
  SECRET_KEY: "ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24="  # base64 encoded
  DB_PASSWORD: "cGFzc3dvcmQ="  # base64 encoded 