apiVersion: v1
kind: Secret
metadata:
  name: calculator-secrets
  namespace: calculator-app
type: Opaque
data:
  # Base64 encoded values (echo -n "password" | base64)
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGNhbGN1bGF0b3ItcG9zdGdyZXM6NTQzMi9jYWxjdWxhdG9yX2Ri"
  REDIS_URL: "cmVkaXM6Ly9jYWxjdWxhdG9yLXJlZGlzOjYzNzk="
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_DB: "Y2FsY3VsYXRvcl9kYg==" 